### ISSUE TITLE
Release new version with supporting django 1.11

### ISSUE THREAD

**Issue by liminspace** [divio/djangocms-column#36] opened 2018-05-19 12:53 UTC
So, I think it's a good idea to release new minor version with supporting django 1.11 even if nothing is done. How do you thing, @czpython?

**Comment by tidenhub** [comment] 2018-05-22 05:59
See #34

**Comment by sammyjava** [comment] 2018-06-21 17:51
It'd be nice, if just to remove the warning whenever you install from pip or do a migrate:
```
djangocms-column 1.7.0 has requirement django<1.10,>=1.8, but you'll have django 1.11.13 which is incompatible.
```

**Comment by stephenrs** [comment] 2018-06-24 20:49
> It'd be nice, if just to remove the warning whenever you install from pip or do a migrate:

I'm honestly not sure "it'd be nice" is a fair characterization of this problem, nor is the term "warning"

This is a blocker to getting the most basic tutorial described here to work: http://docs.django-cms.org/en/latest/introduction/install.html

As a potential new user, who decided on Django CMS after no small amount of research, having it fail miserably within 3 minutes of touching it, obviously I'm not very encouraged, and am forced to refer back to my top list of CMS possibilities.

Hopefully this problem is on the radar of the right people, for the health and adoptability of the project.

**Comment by stephenrs** [comment] 2018-06-24 21:04
Wow, I just realized that changes to support Django 1.11 were allegedly committed **a year ago**

Is this some kind of joke? Am I missing something?

**Comment by liminspace** [comment] 2018-06-24 22:29
@apertureless @astagi @christianbertschy @FinalAngel @glasnt @vxsx @webbyfox take your attention please

**Comment by evildmp** [comment] 2018-06-26 08:31
@liminspace Please don't spray random people with requests. Nearly all of the people you mentioned are not in any position to do anything about this.

@stephenrs When the people who maintain free software encounter criticism of their work that complains it "fails miserably" or asks if "is some kind of joke", we feel quite insulted. Please don't use this kind of language.

Where exactly do you experience a failure? I have just tested the django CMS tutorial, as we do regularly, and have not run into any issues, with:
```
Django==1.11.13
djangocms-column==1.7.0
```
both installed.

Can you provide more information to help reproduce the issue?

django CMS and django CMS Column are both free open-source software. It takes a lot of effort and consumes a lot of time to maintain open-source products, especially in an ecosystem where many individual packages can affect each other.

Volunteers to help improve the situation by offering to package and issue new releases on PyPI will be warmly welcomed.

**Comment by stephenrs** [comment] 2018-06-26 14:07
@evildmp I encountered the error when running the following step of the tutorial:

> djangocms -f -p . mysite

I apologize if relaying my honest experience hurt your feelings, but please spare me and others the sanctimonious lecture. When a tutorial fails this at this early phase in testing a project, it is fairly referred to as a miserable failure == a complete block. When a fix for a problem that is happening today was committed to a repo over a year ago, but has been ignored for that length of time, causing me, and no doubt others, to waste their time, it indeed feels like a mean joke - too strange to be seriously happening. Try to put yourself in another person's shoes.

In any case, I decided to build djangocms-column from master to try to complete my evaluation. However, once past that initial step, I found that the tutorial documentation was so far out of sync with what I was seeing on my screen, that it struck "developer terror" in me. Most notably, when I was finally able to run "python manage.py runserver" as instructed in the tutorial, I did not see a "Welcome to Django CMS" screen - I saw a login screen, with no indication anywhere in the tutorial docs of how to log in.

I googled around to find out how to create a superuser and log in, but the tutorial steps continued to be completely disassociated from what was actually happening in front of my eyes.

I am a long time supporter and contributor to dozens of open source projects over the past 20 years, and I know a poorly maintained one, and surly self-righteous maintainers, when I see it. I've moved on. 

Best of luck with the project.

**Comment by mnieber** [comment] 2018-06-26 22:16
@evildmp I'm running into the same issue when calling `djangocms` to install into a freshly created virtualenv.

My command line call is `djangocms -f --django-version stable -p django_cms django_cms`.

The error is the same as reported above:
djangocms-column 1.7.0 has requirement django<1.10,>=1.8, but you'll have django 1.11.13 which is incompatible

**Comment by stephenrs** [comment] 2018-06-27 04:50
While I'm glad to see that @evildmp is clawing out of the toxic sludge of "it works for me"...and there's much more that I could say in response to what I've experienced in my brief encounter with the people behind this project, there's one thing that I'm unable to withhold...

Most people who know me, particularly non-technical people, have at one time or another received a link to the GNU Manifesto from me. I personally read it a few times a year as a sanity check: https://www.gnu.org/gnu/manifesto.en.html

I mention this in the context of @evildmp's comment:

> django CMS and django CMS Column are both free open-source software.

It honestly didn't sound to me that you have fully understood and internalized the meaning of the word "free" in the context of open source software, or the man who conceived of it. If you've never read the GNU manifesto, you should do it right now.

I have no interest in conflict with anyone, particularly with people who are engaged in doing the same thing that I love to do: building tech stuff. However, when the response to the report of a problem doesn't begin with "Since I've taken responsibility for this project, and am aware that I'm being judged in the context of all other FREE projects, I'm sorry that my team's neglect of the bare essentials have wasted your time", but rather a lecture about my chosen language to report the glaring problem, I'm even less encouraged about a project than I was when it failed miserably in the first place.

Most of us know the red flags of a project to stay away from. Since I was only able to get to "He" of "Hello World" with djangocms, and was scolded by one of the developers for "complaining" about it, I can confidently add djangocms to my list of projects to stay away from.

And @evildmp, while this reality might hurt your precious, all important, feelings, perhaps a more realistic and compassionate way to look at it is that I'm performing a public service - so that others who encounter the problems that I did don't end up wasting as much time as I did. Of course, only if you can accept that this is not all about you. 

Building software is hard. I know. Managing OSS projects is full of challenges. I know - and I'm full of gratitude that Richard Stallman gave us all this amazing idea, and for all the people who keep it alive. This is something that drives me.

So, as a person who thinks he understands your little project in its appropriate perspective, I stand by my assessment, and again wish you luck with the project.

**Comment by stephenrs** [comment] 2018-06-27 05:44
(Sorry, being lectured about OSS by a child who clearly doesn't even know what it is, seemed to deserve a response.)

**Comment by mnieber** [comment] 2018-06-27 06:16
Hi @evildmp, 

I'm using Python 3.5.2 and pip 10.0.1. 

For some reason, I'm getting different results in my docker environment (where it breaks) and in my host environment (where it works). In the latter, I see the same error about `djangocms-column 1.7.0` but there the installation continues. In the docker environment, it stops. In both environments, the python and pip versions are the same.

Best,
Maarten

ps this is the full stack trace

(env) root@b425b020a68f:/srv/linsci/src/website# djangocms -f --django-version stable -p django_cms django_cms
Creating the project
Please wait while I install dependencies
If I am stuck for a long time, please check for connectivity / PyPi issues
djangocms-column 1.7.0 has requirement django<1.10,>=1.8, but you'll have django 1.11.13 which is incompatible.
Dependencies installed
Creating the project
The installation has failed.


*****************************************************************

Check documentation at https://djangocms-installer.readthedocs.io

*****************************************************************

Traceback (most recent call last):
  File "/srv/linsci/env/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/srv/linsci/env/lib/python3.5/site-packages/djangocms_installer/main.py", line 40, in execute
    django.create_project(config_data)
  File "/srv/linsci/env/lib/python3.5/site-packages/djangocms_installer/django/__init__.py", line 61, in create_project
    output = subprocess.check_output(cmd_args, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/srv/linsci/env/bin/python3.5', '/srv/linsci/env/bin/django-admin.py', 'startproject', 'django_cms', '/srv/linsci/src/website/django_cms']' returned non-zero exit status 1

**Comment by evildmp** [comment] 2018-06-27 06:30
Thanks for the feedback @mnieber. It looks like `pip>=10.0.1.` raises the warning, but earlier versions do not. 

Can you do a further test - in the Docker environment, `pip install pip==10.0.0`, then try again? I would like to ascertain whether the error is actually related to the warning.

**Comment by evildmp** [comment] 2018-06-27 06:43
@yakky Any idea why the django CMS Installer might [fail in a Docker environment, but not on the host](https://github.com/divio/djangocms-column/issues/36#issuecomment-400555231) (or if this is related to the warning)?

**Comment by mnieber** [comment] 2018-06-27 07:44
@evildmp I retried with a new virtualenv in which I installed pip 10.0.0 like you suggested. However, the `djangocms` call failed with the same error. Also, note that when I tried in my host environment, I used pip 10.0.1 and it worked there, so I don't think the pip version is the problem.

**Comment by evildmp** [comment] 2018-06-27 10:08
@mnieber I agree. 

Can you run the command again, with the ``--verbose`` flag?

**Comment by mnieber** [comment] 2018-06-27 10:31
@evildmp Thanks, the `--verbose` flag helped me find the problem! In the docker environment, I had DJANGO_SETTINGS_MODULE defined (to a value that is not compatible with the djangocms project layout). 

I guess this problem could be detected early by letting djangocms-installer check that there is no DJANGO_SETTINGS_MODULE environment variable pointing to the wrong value.

**Comment by evildmp** [comment] 2018-06-27 11:38
@mnieber Thanks, I will forward this information to the author of djangocms-installer.

**Comment by evildmp** [comment] 2018-06-27 11:40
Closing as no further information has been provided to reproduce other instances of the reported issue.

**Closed by evildmp** 2018-06-27 11:40 UTC

**Comment by tidenhub** [comment] 2018-06-27 12:37
@evildmp The ticket was created cause the current release 1.7 says 'django>=1.8,<1.11' in setup.py.
If you test the requirements of the Python packages with the latest release you will still get the error:
`djangocms-column 1.7.0 has requirement django<1.11,>=1.8, but you'll have django 1.11.13 which is incompatible.`

**Comment by liminspace** [comment] 2018-06-27 13:00
so, I see it is very difficult to release new minor version. grief

**Comment by evildmp** [comment] 2018-06-27 13:11
@tidenhub That's a warning, rather than an error (still not ideal of course).

djangocms-column does need a new release, but there's already an issue open for that https://github.com/divio/djangocms-column/issues/34.  It'll need to wait though until someone is available to make the release.

**Comment by liminspace** [comment] 2018-06-27 13:54
yes, we need wait one year more to release the minor version as it is very long and difficult process :laughing:

**Comment by ubernostrum** [comment] 2018-06-27 21:29
@stephenrs "Building software is hard."

Yes, doubly so with people like you around to "help".

If all you have to offer is lectures on how everyone but you is doing things wrong, you don't have anything useful to offer. Please let people who are trying to solve problems have the space to do that in.

**Comment by evildmp** [comment] 2018-06-28 13:07
@liminspace You seem to be implying that releasing a new version of a package to PyPI doesn't take long and isn't difficult. 

I've never done it before, and and I don't know what's involved, so you may be right.

If you do know how to do it and are willing to help guide me through the process for the first time, I'd be most grateful and it will help resolve this issue. There isn't anyone else available at present to do it.

**Comment by liminspace** [comment] 2018-06-28 13:34
@evildmp releasing usually takes less than 10 minutes if everything is automated.
For example I just merge new version into master branch and run `python tools.py release` for my libraries like https://github.com/liminspace/django-mjml and new version is published in pypi.
You can see `django-mjml` repository and get to know how releasing is doing by reading files `setup.py`, `setup.cfg`, `tools.py`, `MANIFEST.in`. And, of course, this https://packaging.python.org/tutorials/packaging-projects/ but I use twine to upload, see https://twine.readthedocs.io/en/latest/
I thought divio-community is contains of hi-level developers who have a lot of experience and prefer doing than speaking.
If I can help you, just ask me.

**Comment by stephenrs** [comment] 2018-06-28 14:43
> @tidenhub That's a warning, rather than an error (still not ideal of course).

A warning? ...even though anyone trying to onboard using your tutorial is stopped in their tracks at this point? Maybe it's a warning in your dev environment, but It's a fatal error for anyone trying to get started or evaluate djangocms. 

I'm honestly in shock that no one wants to do the world, and the project, a favor and tag/release the year old fix. Indefensible. IMHO.

**Comment by stephenrs** [comment] 2018-06-28 15:04
just noticed this:

> If all you have to offer is lectures on how everyone but you is doing things wrong, you don't have anything useful to offer. Please let people who are trying to solve problems have the space to do that in.

There's not much I can do here to help - I'm just a user in this project's context, and I've done everything I can figure how to do on my own to get djangocms to do something useful, and to inform others, with no luck, as above.

And if by "everyone" you mean @evildmp - yes, this thread could be used as part of a course on "how to identify an extremely unhealthy project".

Unsubscribing now, this is a pointless distraction for me. Good luck, find someone else to pick on, and something else to whine about, rather than doing the work of good software development.

**Comment by evildmp** [comment] 2018-06-28 16:54
@liminspace 

> I thought divio-community is contains of hi-level developers who have a lot of experience and prefer doing than speaking.

The django CMS community is composed of people with various different kinds and levels of expertise and contributions to make, and not all of them are even developers. 

How long does the release process take? Perhaps you'd be able to join me on IRC or Hangout to help guide me through it. That would be great. Thank you.

**Comment by liminspace** [comment] 2018-06-28 23:01
I use the telegram. My username is the same as here.

**Comment by evildmp** [comment] 2018-06-29 09:00
@liminspace OK. I am on holiday today, but I will ping you tomorrow.

**Comment by evildmp** [comment] 2018-07-06 12:55
Version 1.8.0 has been released to PyPI, thanks @czpython.
